# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
from dateutil.relativedelta import relativedelta
import mysql.connector


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root",
  database="mobile_shop"
)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 1261, 176))
        self.listWidget.setObjectName("listWidget")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 400, 1261, 199))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 3, 2, 1, 1)
        self.label_Total_Cost = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Total_Cost.setFont(font)
        self.label_Total_Cost.setObjectName("label_Total_Cost")
        self.gridLayout.addWidget(self.label_Total_Cost, 2, 0, 2, 1)
        self.label_Pro_Selling = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pro_Selling.setFont(font)
        self.label_Pro_Selling.setObjectName("label_Pro_Selling")
        self.gridLayout.addWidget(self.label_Pro_Selling, 2, 1, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 2, 1, 1)
        self.label_Pro_Rat = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pro_Rat.setFont(font)
        self.label_Pro_Rat.setObjectName("label_Pro_Rat")
        self.gridLayout.addWidget(self.label_Pro_Rat, 6, 1, 3, 1)
        self.label_Net_Pro = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Net_Pro.setFont(font)
        self.label_Net_Pro.setObjectName("label_Net_Pro")
        self.gridLayout.addWidget(self.label_Net_Pro, 6, 0, 3, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 7, 2, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 225, 1261, 171))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.label.setObjectName("label")
        self.pushButton_Search = QtWidgets.QPushButton(Dialog)
        self.pushButton_Search.setGeometry(QtCore.QRect(480, 650, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setObjectName("pushButton_Search")
        
        yearBefore = datetime.now() - relativedelta(months=1)
        self.dateTimeEdit.setDateTime(yearBefore)
        dayBefore = datetime.now()
        self.dateTimeEdit_2.setDateTime(dayBefore)
        
        self.pushButton_Search.clicked.connect(self.Search)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Make Your Report"))
        self.label_2.setText(_translate("Dialog", "Total Cost : ثمن البضاعة المباعة + المصاريف"))
        self.label_7.setText(_translate("Dialog", "Profit rate"))
        self.label_3.setText(_translate("Dialog", "Profit from selling :"))
        self.label_11.setText(_translate("Dialog", "Date and Time"))
        self.label_Total_Cost.setText(_translate("Dialog", " "))
        self.label_Pro_Selling.setText(_translate("Dialog", " "))
        self.label_5.setText(_translate("Dialog", "Net profit :"))
        self.label_13.setText(_translate("Dialog", "to"))
        self.label_Pro_Rat.setText(_translate("Dialog", " "))
        self.label_Net_Pro.setText(_translate("Dialog", " "))
        self.label_14.setText(_translate("Dialog", "Cost"))
        self.label.setText(_translate("Dialog", "Receipt"))
        self.pushButton_Search.setText(_translate("Dialog", "Search"))
        self.Search()
    
    def Search(self):

        self.listWidget_2.clear()
        elements = ["Id"+" "*(15-len("Id")),"Name"+" "*(35-len("Name")),"Much"+" "*(15-len("Much")),"Time and Date"]
        y = " | ".join(elements)
        listWidgetItem = QtWidgets.QListWidgetItem(y)
        listWidgetItem.setFlags(QtCore.Qt.NoItemFlags)
        self.listWidget_2.addItem(listWidgetItem)
        self.listWidget_2.setFont(QtGui.QFont('Roboto Mono', 10))
        
        time = str(self.dateTimeEdit.dateTime())[23:][:-1]
        timeData = time.split(", ")
        dateFrom = timeData[0] + "-" + "{:02d}".format(int(timeData[1])) + "-" + "{:02d}".format(int(timeData[2]))  + " " + "{:02d}".format(int(timeData[3])) + ":" + "{:02d}".format(int(timeData[4]))
        time2 = str(self.dateTimeEdit_2.dateTime())[23:][:-1]
        timeData2 = time2.split(", ")
        dateTo = timeData2[0] + "-" + "{:02d}".format(int(timeData2[1])) + "-" + "{:02d}".format(int(timeData2[2])) + " " + "{:02d}".format(int(timeData2[3])) + ":" + "{:02d}".format(int(timeData2[4])+1)
        
        mydb.reconnect()
        mycursor = mydb.cursor()
        sql = "SELECT * FROM cost WHERE release_date BETWEEN '{}' AND '{}' ".format(dateFrom,dateTo)
        mycursor.execute(sql)
        myresult = mycursor.fetchall()
        mydb.reconnect()
        totalCost = 0
        for element in myresult:
            listOfColumns=[str(element[0]).title()+" "*(15-len(str(element[0]))),str(element[1]).title()+" "*(35-len(element[1])),str(element[2]).title()+" "*(15-len(str(element[2]))),str(element[3]).title()]
            totalCost = totalCost + element[2]
            Result = " | ".join(listOfColumns)
            print(Result)
            listWidgetItem = QtWidgets.QListWidgetItem(Result)
            self.listWidget_2.addItem(listWidgetItem)
            self.listWidget_2.setFont(QtGui.QFont('Roboto Mono', 10))
        
        self.listWidget.clear()
        
        elements = ["Receipt Id"+" "*(20-len("Receipt Id")),"Product Id"+" "*(20-len("Product Id")),"Brand"+" "*(20-len("Brand")),"Model"+" "*(20-len("Model")),"Price on you"+" "*(20-len("Price on you")),"Profit"+" "*(20-len("Profit")),"Number"+" "*(10-len("Number")),"Date and Time"+" "*(20-len("Date and Time"))]
        y = " | ".join(elements)
        listWidgetItem = QtWidgets.QListWidgetItem(y)
        listWidgetItem.setFlags(QtCore.Qt.NoItemFlags)
        self.listWidget.addItem(listWidgetItem)
        self.listWidget.setFont(QtGui.QFont('Roboto Mono', 10))
        
        mydb.reconnect()
        mycursor = mydb.cursor()
        sql = "SELECT * FROM receipt WHERE release_date BETWEEN '{}' AND '{}'".format(dateFrom,dateTo)
        mycursor.execute(sql)
        myresult = mycursor.fetchall()
        mydb.reconnect()
        sellProfit = 0
        totalPro = 0
        for element in myresult:
            totalPro = totalPro + element[4]
            sellProfit = sellProfit + element[5]
            x = 0
            listOfColumns=[]
            mydb.reconnect()
            mycursor = mydb.cursor()
            sql = "SELECT brand, model FROM mobile_devices WHERE serial_id = '{}'".format(element[1])
            mycursor.execute(sql)
            myresult = mycursor.fetchall()
            mydb.reconnect()
            if not myresult:
                mydb.reconnect()
                mycursor = mydb.cursor()
                sql = "SELECT acc_name, brand, kind FROM accessories WHERE acc_id = '{}'".format(element[1])
                mycursor.execute(sql)
                myresult = mycursor.fetchall()
                mydb.reconnect()
            
            for eachElement in element:
                x +=1
                eachElement = str(eachElement).title()
                if x == 3:
                    eachElement = myresult[0][0] + (" " * (20-len(myresult[0][0])))
                    listOfColumns.append((str(eachElement)))
                    continue
                if x == 4:
                    eachElement = " for ".join(myresult[0][1:3]) + (" " * (20-len(" for ".join(myresult[0][1:3]))))
                    listOfColumns.append((str(eachElement)))
                    continue
                if x == 7:
                    eachElement = eachElement + (" " * (10-len(eachElement)))
                    listOfColumns.append((str(eachElement)))
                    continue
                eachElement = eachElement + (" " * (20-len(eachElement)))
                listOfColumns.append((str(eachElement)))
            Result = " | ".join(listOfColumns)
            print(Result)
            listWidgetItem = QtWidgets.QListWidgetItem(Result)
            self.listWidget.addItem(listWidgetItem)
            self.listWidget.setFont(QtGui.QFont('Roboto Mono', 10))
        
        comLoss = str(totalCost) + " + " + str(totalPro) + " = " + str(totalCost + totalPro)
        self.label_Total_Cost.setText(comLoss)
        self.label_Pro_Selling.setText(str(sellProfit))
        self.label_Net_Pro.setText(str(sellProfit - totalCost))
        nuu = (sellProfit - totalCost) / (totalCost + totalPro)
        self.label_Pro_Rat.setText(str(round(nuu * 100 ,4)) + " %")
